version: '3.2'
services:
  api:
    build:
      context: ./backend
    networks:
      - db-net
    volumes:
      - ./backend:/api/ticket
      - /api/ticket/node_modules
    ports:
      - "5000:5000"
    env_file:
      - .env_backend

networks:
  db-net: